export const items = [
    {
      id: 1,
      title: 'telluride',
      category: 'mountain',
      price: 15.99,
      img: 'https://www.google.com/url?sa=i&url=http%3A%2F%2Ft3.gstatic.com%2Flicensed-image%3Fq%3Dtbn%3AANd9GcSVjTkLvmTnLskhcGU2GxvSubq7lJ0uk75_MrYAoYgpnB1J6iN2oFGzjWdbIomIJQKT&psig=AOvVaw3y3S4_JxJwtD_DegAHSdfi&ust=1690701432074000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCOig8-avs4ADFQAAAAAdAAAAABAE',
      desc: `Telluride, a former Victorian mining town in Colorado’s Rocky Mountains, is set in a box canyon amid forested peaks at the base of a popular ski-and-golf resort. `,
    },
    {
      id: 2,
      title: 'asheville',
      category: 'mountain',
      price: 15.99,
      img: 'https://www.google.com/url?sa=i&url=http%3A%2F%2Ft2.gstatic.com%2Flicensed-image%3Fq%3Dtbn%3AANd9GcQnc9NHESRnp3c0iERAGAqjuHB1mniC_-t-ny5Vi1F-xoXwOkHfQIDSYuIPM0a6CYcP&psig=AOvVaw3y3S4_JxJwtD_DegAHSdfi&ust=1690701432074000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKii8aWws4ADFQAAAAAdAAAAABAE',
      desc: `Asheville is a city in western North Carolina’s Blue Ridge Mountains which is known for vibrant arts scene and historic architecture, including the dome-topped Basilica of Saint Lawrence. `,
    },
    {
      id: 3,
      title: 'kovalam',
      category: 'beach',
      price: 13.99,
      img: 'https://www.google.com/url?sa=i&url=http%3A%2F%2Ft2.gstatic.com%2Flicensed-image%3Fq%3Dtbn%3AANd9GcT8zoOuTAmyxqCUot6kEXd65jI7ZfsC9rlwzGqag6ryqkX5f_l42GR6rqThxQ4JdiuH&psig=AOvVaw3Pi0wCCwibp3DSwu3RCe3z&ust=1690701653240000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCOjHkNaws4ADFQAAAAAdAAAAABAI',
      desc: `Ovalam is a small coastal town in the southern Indian state of Kerala, south of Thiruvananthapuram having Lighthouse Beach with a viewing platform.`,
    },
    {
      id: 4,
      title: 'maldevis',
      category: 'beach',
      price: 13.99,
      img: 'https://hblimg.mmtcdn.com/content/hubble/img/maldives/mmt/destination/m_Maldives_l_400_640.jpg',
      desc: ` A delightful beach vacay awaits you at Maldives. You will love the beach activities and island hopping. Maldives is also an ideal destination for a relaxing break.`,
    },
    {
      id: 5,
      title: 'Krabi',
      category: 'beach',
      price: 13.99,
      img: 'https://hblimg.mmtcdn.com/content/hubble/img/krabi/mmt/destination/m_krabi-landscape_l_400_640.jpg',
      desc: ` Krabi is home to serene beaches. You will love the beaches and water sports. Krabi is also an ideal destination for a relaxing break.`,
    },
    {
      id: 6,
      title: 'hallstaff',
      category: 'mountain',
      price: 6.99,
      img: 'https://hips.hearstapps.com/hmg-prod/images/vienna-gettyimages-1074275882-64c2cf92da0d5.jpg?crop=1xw:1xh;center,top&resize=980:*',
      desc: ` Inspiring the settings in Disney’s Frozen movies, Hallstatt, Austria, is a tiny Alpine village between Salzburg and Vienna.It’s also a popular day trip destination thanks to its scenic lake views and charming Old Town.`,
    },
    {
      id: 7,
      title: 'the scottish highlands',
      category: 'mountain',
      price: 20.99,
      img: 'https://hips.hearstapps.com/hmg-prod/images/highlands-gettyimages-1372853458-64c2c72bbf03d.jpg?crop=1xw:1xh;center,top&resize=980:*',
      desc: ` U.K.’s largest, the Scottish Highlands is a picturesque wintry destination. Make an itinerary of the local castles, or stay at the Fife Arms, a former Victorian coaching inn in the town of Braemar, where they host the Highland Games in September. `,
    },
    {
      id: 8,
      title: ' tour du mont blanc',
      category: 'mountain',
      price: 22.99,
      img: 'https://d2z0k43lzfi12d.cloudfront.net/blog/vcdn374/wp-content/uploads/2023/01/STK_top-hiking-_-running-destinations_bp-1-1024x683.jpg.webp',
      desc: ` This world-renowned trail circles peaks in Switzerland, Italy, and France and is 110 miles (170 km) and can typically be walked over the course of 11 days,There are variations in the trail route, and some offer more challenges and viewpoints than the alternative`,
    },
    {
      id: 9,
      title: 'consta brava trails',
      category: 'mountain',
      price: 18.99,
      img: 'https://d2z0k43lzfi12d.cloudfront.net/blog/vcdn374/wp-content/uploads/2023/01/STK_top-hiking-_-running-destinations_bp-4-1024x683.jpg.webp',
      desc: `This running destination is perfect for those looking for culture, beauty, and activity. Visitors can easily spend a week running various trails, moving from the seaside to the hillside, stopping at museums along the way, and indulging in delicious local cuisine.`,
    },
    {
      id: 10,
      title: 'sossus dune lodge, namibia',
      category: 'desert',
      price: 18.99,
      img: 'https://cdn.outsideonline.com/wp-content/uploads/migrated-images_parent/migrated-images_44/OO_Namibia_04262012.jpg?width=800',
      desc: `Namibia is one of those rare conservation success stories where wildlife recovery is on the rise, 42 percent of the land is under conservation management, and the country’s entire 1,000-mile coastline is protected. The southern African country also claims the Namib, the world’s oldest desert, which is home to the world’s second-highest sand dunes that top out at nearly 1,000 feet.`,
    },
    {
      id: 11,
      title: 'villa santa cruz',
      category: 'desert',
      price: 18.99,
      img: 'https://cdn.outsideonline.com/wp-content/uploads/migrated-images_parent/migrated-images_44/OO_Villa_04262012.jpg?width=800',
      desc:`This beautiful adobe hacienda with a soft orange patina sits on 20 acres of secluded beachfront property. The four-suite casa, which was built in 2006 but was designed to appear as if it had been there for hundreds of years, is powered almost entirely by solar electricity, the clean linens are line-dried in the desert breeze, and all meals are made with produce grown in the on-site vegetable garden.`,
    },
    {
      id: 12,
      title: 'machu picchu',
      category: 'mountain',
      price: 8.99,
      img: 'https://media.nomadicmatt.com/historical-machu.jpg',
      desc: `More than 7,000 feet above sea level in the Andes Mountains, Machu Picchu is the most visited tourist destination in Peru. A symbol of the Incan Empire and built around 1450AD, Machu Picchu was designated a UNESCO World Heritage Site in 1983 and was named one of the New Seven Wonders of the World in 2007. 10`,
    }
  ];
